### ISSUE TITLE
This command fails  vmq-admin session show --client_id=client1

### ISSUE THREAD

**Issue by orestes22** [vernemq/vernemq#1436]
### To help us save time and help you faster

vmq-admin session show --client_id=client1

This command fails when client_id parameter is a string composed by only numbers like "1234567890"

### Environment

- VerneMQ Version: 1.10
- OS: Kubernetes 
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone: 

### Expected behavior

- It should be work equal with number and characters 

### Actual behaviour

- This command fails when client_id parameter is a string composed by only numbers like "1234567890"

**Comment by ioolkos** [comment]
Must be a bug, if it's not some issue about espacing characters in the shell.
Thanks for the observation @orestes22!

**Comment by orestes22** [comment]
Thanks for read the issue. 
Also I want to add this behavior is the same using the API functionality.

Thanks and Best Regards

**Comment by ioolkos** [comment]
@orestes22 can you test PR https://github.com/vernemq/vernemq/pull/1437 ?

**Comment by orestes22** [comment]
Hi @ioolkos  , I dont have the correct environment to test it, right now Im using docket and kubernetes, so I only run and image in google cloud. 
Probably if you create a branch with this change i could test it. 

Best Regards

**Comment by ioolkos** [comment]
Should be fixed by merged PR https://github.com/vernemq/vernemq/pull/1437

**Comment by orestes22** [comment]
@ioolkos  Hi, good day, I recently try to use the last version, v1.10.1, this bug isnt fixed. 
Im not sure if you published this change or not,
Please, any feedback ill welcome. 
Best Regards

**Comment by ioolkos** [comment]
No, it's not yet in a released package, but in master.
This stuff is easy to find out by the way...navigating around github.

**Comment by orestes22** [comment]
Thanks for your answer, @ioolkos. I appreciate a lot. However, the main point of last question is when I will have the possibility to test it? 
Is there a schedule for the release?  Im pretty sure the team in charge will be very busy, but i need to implement an feature so i will love to know when i can update and start to program my feature. 
Best Regards

**Comment by cmnstmntmn** [comment]
@orestes22 you may consider to build on your own from the master repo;
see [here](https://vernemq.com/downloads/index.html) how you can do it.

**Comment by orestes22** [comment]
Hi, @cmnstmntmn Do you have experience in create a docker from the repo ? I was trying an im having some issue. Do you have any advice in this area ?
Best Regards

**Comment by ioolkos** [comment]
@orestes22 release 1.10.2 is out now

**Comment by orestes22** [comment]
@ioolkos That version 1.10.2 is crashing right now. 
This is the error : 
---------------------------------------------------------------------------------
I 2020-03-20T14:10:55.219651608Z 14:10:55.191 [info] Application sext exited with reason: stopped
 
I 2020-03-20T14:10:55.219808101Z 14:10:55.193 [info] Application riak_dt exited with reason: stopped
 
I 2020-03-20T14:10:55.219943181Z 14:10:55.194 [info] Application eleveldb exited with reason: stopped
 
I 2020-03-20T14:10:55.225966569Z 14:10:55.201 [error] Loading of /vernemq/bin/../lib/vmq_plumtree-1.10.2/ebin/vmq_plumtree.beam failed: not_purged
 
I 2020-03-20T14:10:55.232280471Z 14:10:55.231 [warning] The on_load function for module eleveldb returned:
 
I 2020-03-20T14:10:55.232325896Z {error,{load_failed,"Failed to load NIF library /vernemq/bin/../lib/eleveldb-2.0.2+build.552.ref06fefb8/priv/eleveldb: 'libsnappy.so.1: cannot open shared object file: No such file or directory'"}}
 
I 2020-03-20T14:10:55.241767043Z 14:10:55.233 [error] CRASH REPORT Process <0.227.0> with 0 neighbours crashed with reason: call to undefined function eleveldb:validate_options(open, [{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,...},...])
 
I 2020-03-20T14:10:55.249157137Z 14:10:55.236 [error] CRASH REPORT Process <0.224.0> with 0 neighbours exited with reason: no match of right hand value {error,{{undef,[{eleveldb,validate_options,[open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{data,[{dir,"./data"}]},{data_root,"./data/leveldb"},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{store_dir,"./data/msgstore"},{sync,false},{tiered_slow_level,0},{total_leveldb_mem_percent,70},{use_bloomfilter,true},{verify_checksums,true},...]],...},...]},...}} in vmq_generic_msg_store_sup:'-start_link/0-lc$^0/1-0-'/2 line 40 in application_master:init/4 line 138
 
I 2020-03-20T14:10:55.249396168Z 14:10:55.238 [info] Application vmq_generic_msg_store exited with reason: no match of right hand value {error,{{undef,[{eleveldb,validate_options,[open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{data,[{dir,"./data"}]},{data_root,"./data/leveldb"},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{store_dir,"./data/msgstore"},{sync,false},{tiered_slow_level,0},{total_leveldb_mem_percent,70},{use_bloomfilter,true},{verify_checksums,true},...]],...},...]},...}} in vmq_generic_msg_store_sup:'-start_link/0-lc$^0/1-0-'/2 line 40
 
I 2020-03-20T14:10:55.256068273Z 14:10:55.250 [error] gen_server vmq_plugin_mgr terminated with reason: no match of right hand value {error,{vmq_generic_msg_store,{bad_return,{{vmq_generic_msg_store_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{undef,[{eleveldb,validate_options,[open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{data,[{dir,"./data"}]},{data_root,"./data/leveldb"},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{store_dir,"./data/msgstore"},{sync,...},...]],...},...]},...}}},...}}}}}} in vmq_plugin_mgr:start_plugin/1 line 524
 
I 2020-03-20T14:10:55.267683919Z 14:10:55.253 [error] CRASH REPORT Process vmq_plugin_mgr with 1 neighbours crashed with reason: no match of right hand value {error,{vmq_generic_msg_store,{bad_return,{{vmq_generic_msg_store_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{undef,[{eleveldb,validate_options,[open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{data,[{dir,"./data"}]},{data_root,"./data/leveldb"},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{store_dir,"./data/msgstore"},{sync,...},...]],...},...]},...}}},...}}}}}} in vmq_plugin_mgr:start_plugin/1 line 524
 
I 2020-03-20T14:10:55.286946992Z 14:10:55.255 [error] Supervisor vmq_plugin_sup had child vmq_plugin_mgr started with vmq_plugin_mgr:start_link() at <0.190.0> exit with reason no match of right hand value {error,{vmq_generic_msg_store,{bad_return,{{vmq_generic_msg_store_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{undef,[{eleveldb,validate_options,[open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{data,[{dir,"./data"}]},{data_root,"./data/leveldb"},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{store_dir,"./data/msgstore"},{sync,...},...]],...},...]},...}}},...}}}}}} in vmq_plugin_mgr:start_plugin/1 line 524 in context child_terminated
 
E 2020-03-20T14:10:55.288088541Z [os_mon] memory supervisor port (memsup): Erlang has closed
 
E 2020-03-20T14:10:55.288108612Z [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
----------------------------------------------------------------------------------

**Comment by orestes22** [comment]
@ioolkos The above is in kubernetes cluster in google cloud engine

**Comment by ioolkos** [comment]
What version is this and what exactly did you do?

**Comment by orestes22** [comment]
The version is 1.10.2.alpine, the latest version. 
I only did : 
helm install vernemq/vernemq

**Comment by ioolkos** [comment]
Hm, yep, Docker image seems faulty. Thanks!
@codeadict there's an issue with libsnappy it seems. I maybe need to adapt the Docker images.

**Comment by orestes22** [comment]
Noted @ioolkos, Please, let me know if you need I test again. 

Im doing this because Im following @cmnstmntmn advice, so before this new release I was trying to build my own docker image with no luck. I was having issues with file permissions inside the containers. But I was having the same problem with older versions of vernemq

I will appreciate a lot any advice or orientation I can get to create my docker and have better environment to test

Best Regards

**Comment by orestes22** [comment]
Do you think i would need open a new issue with this topic in the docker-vernemq repo ?

Because the real reason of this issue I cant say i tested, because the above reason explained.

Regards

**Comment by ioolkos** [comment]
no need to open issue

**Comment by ioolkos** [comment]
Could you try with the latest build here? https://hub.docker.com/r/vernemq/vernemq/builds

**Comment by codeadict** [comment]
@ioolkos looks like we need to add libsnappy to the containers. Checking now

**Comment by ioolkos** [comment]
@codeadict did it here: https://github.com/vernemq/docker-vernemq/pull/199 will have to see if this is a definitive fix

**Comment by codeadict** [comment]
Ahh, I see you added it on https://github.com/vernemq/docker-vernemq/commit/61f1f9b8cb6f53e71020a63e7e39fb7b1349a2f6. One thing we must do is to update this information in the website https://vernemq.com/downloads/index.html under `Building VerneMQ from sources`. I mentioned that the other day to somebody in Slack but I don't have acces to the website source code.

**Comment by ioolkos** [comment]
Okay, thanks, I'll update that.

**Comment by codeadict** [comment]
Thanks :)

**Comment by orestes22** [comment]
@ioolkos  I will let you know, that the last version is working fine and the original bug of this open issue is fixed.

**Comment by ioolkos** [comment]
@orestes22 yihaa, thanks :)

**Comment by orestes22** [comment]
yihaa too , :D Im happy to help,,, thanks for you time @ioolkos  

I promise dont disturb more, :) but I'm trying to compile and create my own docker image. I'm having issues creating the image with the proper permissions and user owner, can I have some advice or feedback what i could doing wrong?
