### ISSUE TITLE
Failing state loading after adding API_key

### ISSUE THREAD

**Issue by ioolkos** [vernemq/vernemq#1832]
Possible bug in state loading while booting, after adding an API key to node. Suspecting this is related to the class of issues introduced with 1.12.0 and the changed binary encoding.

```erlang
2021-06-22 21:06:20.653 [error] emulator Error in process <0.286.0> on node 'VerneMQ@127.0.0.1' with exit value:
{badarg,[{erlang,binary_to_term,[<<:::Large Binary:::>>,[safe]],[]},{vmq_swc_store,'-init_dotkeymap/1-fun-1-',4,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,763}]},{vmq_swc_db_leveldb,iterate,6,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_db_leveldb.erl"},{line,138}]},{vmq_swc_db_leveldb,'-handle_call/3-fun-1-',6,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_db_leveldb.erl"},{line,110}]}]}
```

**Comment by ioolkos** [comment]
Should be resolved in 1.12.1. Verification pending.

**Comment by JacoFourie** [comment]
Hi @ioolkos . I have the same issue. I did remove the broker and reinstalled it but I still have this crash. How do I remove the broker completely so I can reinstall it to get it working without the API key?

This is the crash report.

2021-07-20 20:05:56 =ERROR REPORT====
Error in process <0.283.0> on node 'VerneMQ@127.0.0.1' with exit value:
{badarg,[{erlang,binary_to_term,[<<131,104,2,116,0,0,0,1,104,2,104,2,100,0,17,86,101,114,110,101,77,81,64,49,50,55,46,48,46,48,46,49,109,0,0,0,20,69,28,161,239,37,247,102,80,121,196,66,199,188,119,230,89,54,97,47,75,97,6,104,2,104,3,98,0,0,6,90,98,0,10,148,77,98,0,9,50,222,104,5,100,0,10,118,109,113,95,99,111,110,102,105,103,104,2,100,0,10,118,109,113,95,115,101,114,118,101,114,100,0,18,104,116,116,112,95,109,103,109,116,95,97,112,105,95,107,101,121,115,108,0,0,0,1,109,0,0,0,32,72,97,98,49,53,98,71,119,99,57,68,78,113,112,81,66,54,82,122,90,111,122,69,114,48,121,55,89,106,112,73,68,106,100,0,9,117,110,100,101,102,105,110,101,100,100,0,9,117,110,100,101,102,105,110,101,100,116,0,0,0,1,104,2,100,0,17,86,101,114,110,101,77,81,64,49,50,55,46,48,46,48,46,49,109,0,0,0,20,69,28,161,239,37,247,102,80,121,196,66,199,188,119,230,89,54,97,47,75,97,6>>,[safe]],[]},{vmq_swc_store,'-init_dotkeymap/1-fun-1-',4,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_store.erl"},{line,763}]},{vmq_swc_db_leveldb,iterate,6,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_db_leveldb.erl"},{line,138}]},{vmq_swc_db_leveldb,'-handle_call/3-fun-1-',6,[{file,"/opt/vernemq/apps/vmq_swc/src/vmq_swc_db_leveldb.erl"},{line,110}]}]}

**Comment by ioolkos** [comment]
@JacoFourie make sure you remove the data dirs (`/var/lib/vernemq/`). This is about the `cluster_state` file in `swc_meta` specfically. Also, it seems that you still run 1.12.0 here, not 1.12.1

**Comment by JacoFourie** [comment]
Thank you I have it up and running again on the latest version.
